# Site settings
name: Divya Hegde
title: Divya Hegde | AI/ML Engineer
description: AI-focused data scientist passionate about building scalable generative systems that understand and create natural language.
url: https://divyahegde-07.github.io/
baseurl: ''
email: divyahegdefte@gmail.com
cover: https://divyahegde-07.github.io/img/og.png
logo: https://divyahegde-07.github.io/emojis/technologist.png
resume: https://divyahegde-07.github.io/resume.pdf
social:
  - title: email
    url: mailto:divyahegdefte@gmail.com
  - title: medium
    url: https://medium.com/@divyahegde1995
  - title: github
    url: https://github.com/divyahegde-07
  - title: linkedin
    url: https://www.linkedin.com/in/hegdedivya/
  - title: instagram
    url: https://instagram.com/divyahegde95

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
